FROM ponycool/jdk8:1.0
LABEL maintainer="AZKABAN-MULTI-EXECUTOR DOCKER MAINTAINER <pony@ponycool.com>"

# ENV AZK_VERSION 3.81.0

WORKDIR /usr/local/azkaban

ADD azkaban-exec-server-0.1.0-SNAPSHOT.tar.gz ./

RUN buildDeps=" \
    zip \
    " \
    runtimeDeps=" \
        bash \
        curl \
    " \
    && apk update \
    && apk upgrade \
    && apk add --no-cache $buildDeps $runtimeDeps \
    && rm -rf /var/cache/apk/* \
    && mv azkaban-exec-server-0.1.0-SNAPSHOT/* ./ \
    && rm -rf azkaban-exec-server-0.1.0-SNAPSHOT \
    # 关闭内存检查
    && echo -e '\nmemCheck.enabled=false' >> plugins/jobtypes/commonprivate.properties

ADD conf/azkaban.properties conf/azkaban.properties

ADD conf/run.sh run.sh

RUN chmod +x run.sh

CMD [ "./run.sh" ]